MAKECODE102EXT.agentAnalyze(SixDirection.Forward);
MAKECODE102EXT.agentDetectDryFern(SixDirection.Forward);
MAKECODE102EXT.agentDetectDryGrass(SixDirection.Forward);
MAKECODE102EXT.agentDetectDryBrush(SixDirection.Forward);
MAKECODE102EXT.hazardsRemainL4();
MAKECODE102EXT.hazardsRemainL5();
MAKECODE102EXT.hazardsRemainL6();
MAKECODE102EXT.agentDestroyL4(SixDirection.Forward);
MAKECODE102EXT.agentDestroyL5(SixDirection.Forward);
MAKECODE102EXT.agentDestroyL6(SixDirection.Forward);
MAKECODE102EXT.openDoor();
MAKECODE102EXT.completeTask();
MAKECODE102EXT.agentLookForHazards();
MAKECODE102EXT.agentSeeHazard();
MAKECODE102EXT.alertTeam();
MAKECODE102EXT.fakePlace(Block.Grass, SixDirection.Forward);
